import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class AddData extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    CollectionReference restaurants =
        FirebaseFirestore.instance.collection('restaurants');
    // CollectionReference temples = FirebaseFirestore.instance.collection('temples');
    CollectionReference cafes = FirebaseFirestore.instance.collection('cafes');
    CollectionReference places =
        FirebaseFirestore.instance.collection('places');

    Future<void> addPlace() async {
      var names = [
        'Mezze Restaurant',
        'El Dokka Restaurant',
        'Al-Rokn Al-Demashqy Restaurant',
        'EL Masry Restaurant',
        'Makka Restaurant',
        'Makani restaurant',
        'Nubian Dreams Restaurant & Cafe Ali Jamaica',
        'Solaih Nubian Restaurant',
        'Abeer restaurant',
        'Salah el-Din resturant',
        'Bob Marley Guest House & Restaurant & Cafe',
        'Porto Sono',
        'Oriental Kebabgy',
        'Chef Khalil',
        'Old Nubian Guest House and Restaurant',
        'Biti Pizza',
        'Emy Cafeteria & Restaurant',
        'Ibiza Nubian House',
        'Gambari Afandi Seafood',
        'El Salam Nile & Seafood Restaurant',
        'Kato Dool Restaurant & cafe',
        'Alexandria kaman we kaman Restaurant',
        'Strawberry Restaurant',
        'Esmo Eh Restaurant',
        'Grand Restaurant & cafe',
        'Hajah Huluwh Restaurant',
        'Koshary El-safwa',
        'KFC - Aswan',
        'Panorama Restaurant & Bar',
        "McDonald's Restaurant",
        'Ashry Toky',
        'Kingdom of Juventus',
        'QASR EL SHAM RESTURANT',
        'Orangerie Restaurant Aswan',
        'Elmabroka Restaurant And Cafe',
        'Elephantine Restaurant',
        'Osiris Restaurant',
        'Ahmos Restaurant',
        'Huda Palace Restaurant',
        'El-Madinah Restaurant'
      ];
      var desc = [
        ' The Mezze restaurant offers a variety of authentic a` la carte Egyptian food with an indoor and outdoor seating. It is located at the Elephantine wing with a stunning views, directly facing the Nile River, the Botanical Island, the Mausoleum of Aga Khan and the Tomb of the Nobles. Experience the lunch & dinner at historical city like never before',
        ' EL Dokka restaurant offers a variety of authentic a` la carte Egyptian food with an indoor and outdoor seating. It is located at the Elephantine island with a stunning views, Hessa island, 0.6 from temple of philae. Experience the lunch & dinner at historical city like never before',
        ' Therestaurant offers a variety of authentic a` la carte Egyptian food with an indoor and outdoor seating.',
        ' EL Masry restaurant offers a variety of authentic a` la carte Egyptian food with an indoor and outdoor seating. It is located at the Elephantine island with a stunning views, Hessa island, 0.6 from temple of philae. Experience the lunch & dinner at historical city like never before',
        ' Makka restaurant  Near the Station in Aswan, round the corner from the celebrated Chef Khalil restauran',
        ' A Healthy Grill Restaurant with inside and outside seating facilities on the bank of the River Nile',
        ' Fresh, home cooked meals. Chicken, beef, camel, pigeon, fish and vegetable tagine or barbecue. Fresh juices and Nubian Jabana coffee. Alcohol is available as well as many flavours of shisha. Amazing views of The Nile River and Aswan city from the colourfully decorated terrace. Friendly Nubian staff who speak English and Arabic. Nothing is too much trouble to mak',
        ' Nubian kitchen is rich with its recipes, but unfortunately these recipes are not commonly used right now among Nubians and started to disappear. Our aim was to establish a Nubian restaurant that provide only Nubian cuisine with old and new recipes. The restaurant is located in a premium location on an island overlooking the famous Philae temple',
        " Hi everybody,If u come to Aswan try to have a meal in a nice local restaurant.Near railway station is small Abdeli tahrir , street with this name. In the middle of this street is entrance in Abeer restoran. There you can be served by local meat specialty. The best is Koffta, something what you get in Balkans restaurants. It's grilled meat and very tasty. You get near plate of Tahina and vegetable salad. Enough to be eat ones fell.Of corse they serve fresh local bred. All of it cost 15 Egyptian poundsUnfortunately you can get only soft drinks, but it's worth to visit this gastronomic pearl",
        ' Good plac',
        ' Fresh, home cooked meals. Chicken, beef, camel, pigeon, fish and vegetable tagine or barbecue. Fresh juices and Nubian Jabana coffee. Alcohol is available as well as many flavours of shisha. Amazing views of The Nile River and Aswan city from the colourfully decorated terrace. Friendly Nubian staff who speak English and Arabic. Nothing is too much trouble to mak',
        ' New Corniche, Near Al Mawqaf Al Eqlimy, Aswan, Egypt',
        ' Abtal El Tahrir Street, Aswan, Egypt',
        ' Sharia al Souk - End of souk near train station, Aswan, Egyp',
        ' an authentic Nubian restaurant and guesthouse that offers a spectacular view on the Nile river and great authentic Nubian food in a Nubian decoration . during your experience there you will be served by a Nubian waiter and you will find books about the Nubian culture in all languages that will give you an insight into the Nubian and Upper Egyptian culture',
        ' Located in front of the train station, Biti Pizza has pizza, but even better has delicious Egyptian fiteer, a pizza-like Egyptian dish that can be sweet or savory. Bibo, a charming young man, speaks English. Fom the 2nd floor you can watch the square in front of the train statioi',
        ' Having a bite of local Egyptian food at EMY perched right on the bank of the Nile was perfect after a Felluca ride. Good authentic food in an authentic local eatery',
        'Ibiza Nubian House is not just a restaurant. Above the restaurant there is a 2 bedroom self contained apartment available for rent',
        'A local Sea Food Restauran',
        'A local Sea Food Restaurant,the restaurant located near the train station of Aswan',
        'Kato Dool Nubian House, Kato Dool is a Nubian word means "the Big House" Kato Dool is your gateway to the best Nubian Experience in Aswan, the place surrounded by the Nile and simple colored cozy homes that helps your brain to travel away and feel the real meaning of relaxation. The hotel offers 8 different unique bedrooms all are Nile view. And another 5 Triple rooms Nile view too second line. Kato Dool located at the Tourists Dock; Kato Dool is: 8 km. from Aswan international airport. 14 km. from Aswan Train station. 12 km. from the local Aswan market. 6 km. from the High Dam. 8 km. from Philea Temple. Situated on the boardwalk, this historic guesthouse is within 9 mi (15 km) of Philae Temple, Unfinished Obelisk, and High Dam Monument. Nubian Museum and Temple of Kalabsha are also within 9 mi (15 km). We provide a luxury Nubian accommodation at the Nile River, We have a Nubian restaurant with 8 different menus, We serve All kinds of drinks and shisha',
        'Our restaurant welcomes its guests from all over the world to taste our fast and inexpensive Egyptian food',
        'We cook Nubian and Egyptian recipes. Vegans are welcome',
        'Exellent PIZZA resturant, El-Shaheed Abd El-Fattah Hassanein | behinb the government building, Sheyakhah Thalethah, Aswan, Egyp',
        'grand resturant Delicious food,Wonderful landscape A comfortable place to take a check',
        'crepe and dessert resturant, Saad Zaghloul, Abu AR Rish Qebli, Aswan, Egyp',
        'an exellant koshary resturant,Abu AR Rish Qebli, Aswan, Egyp',
        'Chicken resturant',
        'Panorama restaurant had a wonderful food and drink',
        'restaurant had a wonderful food and drink',
        'exellent nubian resturant',
        'PS3 PS4 gaming center restaurant and cafe, 5 stars entrance underground , super Air conditioning , Big LED screens , 2 big sofas ber screen ',
        'SHAWRMA AND PIZZA RESTURAN',
        'Good resturant and cadfe',
        'restaurant had a wonderful food and drink',
        'restaurant had a wonderful food and drink',
        'restaurant had a wonderful food and drink',
        'restaurant had a wonderful food and drink',
        'restaurant had a wonderful food and drink',
        'restaurant had a wonderful food and drink'
      ];
      var froms = [
        ' 12 AM',
        ' 8 AM',
        ' 9 AM',
        ' 8 AM',
        ' 12:00 PM',
        ' 12:00 AM',
        ' 12:00 AM',
        ' 10:00 AM',
        ' 9:00 AM',
        ' 10:00 AM',
        ' 12:00 PM',
        ' 10:00 AM',
        ' 07:00 PM',
        ' 9:00 AM',
        ' 12:00 AM',
        ' 10:00 AM',
        ' 10:00 AM',
        ' 10:00 AM',
        ' 9:00 AM',
        ' 8:00 AM',
        ' 8:00 AM',
        ' 12:00 AM',
        ' 12:00 AM',
        ' 11:00 AM',
        ' 12:00 AM',
        ' 04:00 PM',
        ' 12:00 AM',
        ' 11:00 AM',
        ' 12:00 AM',
        ' 07:00 AM',
        ' 07:30 AM',
        ' 12:00 AM',
        ' 09:00 AM',
        ' 06:00 AM',
        ' 11:00 AM',
        ' 06:00 AM',
        ' 06:00 AM',
        ' 09:00 AM',
        ' 11:00 AM',
        ' 09:00 AM'
      ];
      var tos = [
        ' 11:59 PM',
        ' 11:59 PM',
        ' 03:00 AM',
        ' 11:59 PM',
        ' 12:00 AM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 10:00 PM',
        ' 11:59 PM',
        ' 2:00 AM',
        ' 11:59 PM',
        ' 2:00 AM',
        ' 12:00 AM',
        ' 12:00 AM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 11:45 PM',
        ' 11:45 PM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 01:30 AM',
        ' 11:59 PM',
        ' 03:00 AM',
        ' 11:59 PM',
        ' 03:00 AM',
        ' 11:59 PM',
        ' 02:00 PM',
        ' 01:00 AM',
        ' 11:59 PM',
        ' 11:59 PM',
        ' 10:00 PM',
        ' 11:00 PM',
        ' 11:00 PM',
        ' 11:00 PM',
        ' 11:00 PM',
        ' 03:00 AM',
        ' 12:00 AM'
      ];
      var images = [
        'https://media-cdn.tripadvisor.com/media/photo-s/1a/a4/f2/23/enjoy-the-taste-of-the.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-p/12/41/42/83/photo2jpg.jpg',
        'https://lh5.googleusercontent.com/p/AF1QipNsPjOxvxZPXdCKQVaD0W4eJGbCdAoH3WB3ikqg=w203-h114-k-no',
        'https://media-cdn.tripadvisor.com/media/photo-s/10/1a/a7/0f/salle-du-restaurant.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/11/91/f7/38/20171214-181827-largejpg.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/17/64/9a/de/makani.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1c/83/50/09/bob-marley-moonlight.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/15/3b/fd/be/getlstd-property-photo.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1a/08/d8/a4/caption.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/01/ea/32/12/awan-resto-salah-ed-din.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1c/b1/08/5c/img-20210228-173834-largejpg.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/03/c9/93/d7/porto-sono.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/13/e2/78/3e/salle-interieure-du-restaurant.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/0e/b5/60/c1/20170319-162235-largejpg.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1c/c9/58/a0/old-nubian-guest-house.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/02/3b/52/6b/delicious-pizza.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1c/91/3c/89/photo0jpg.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/16/34/c0/c7/ibiza-nubian-house.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1b/68/55/9b/gambari-afandi-seafood.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/09/e8/8d/85/fried-tiliapa-fish.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/11/89/e8/8b/getlstd-property-photo.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-o/1b/73/b0/a6/getlstd-property-photo.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-f/1b/e9/3e/a6/fresh-and-tasty.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1a/39/ff/40/pizza-esmo-a.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/13/91/f2/74/caption.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1a/94/31/b6/caption.jpg',
        'https://media-cdn.tripadvisor.com/media/photo-s/1c/92/12/4f/pxl-20210120-191842954.jpg',
        'https://lh5.googleusercontent.com/p/AF1QipNMnqkfAfgQ3LUxm6_efWmxMPyye8Q8Uk_eJMlL=s508-k-no',
        'https://media-cdn.tripadvisor.com/media/photo-s/16/92/c7/af/img-20190224-wa0026-largejpg.jpg',
        'https://lh5.googleusercontent.com/p/AF1QipOja4JBfrBGz9H5k20lFV15QtZJEu-BdLNGJIDF=w408-h544-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipNFP26LPEhGaabelBj-vJ15Omjes_4k_pdRHQfu=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipPsMUuhtJJeaLRU2g9f4wb_TbgvzzIhtvCso5_H=w408-h272-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipMQxWrlsGYL7fI7hfF4s3g70kxHAfPt9Ahcbcnp=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipMbcHujyD_6lcJjvC7_DXft-UeF_9A_SSLUglgj=w408-h272-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipOBnH5PfVWvi4YnEl0hzqCXpAi2m7AyFKzpd9wk=w427-h240-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipOn8jgQ5E2vTeGX5gKN13zY4icN2Ms56WK04Cec=w408-h611-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipOoBd_QY-rSEhKForbVIVrX-To_bNIMqYt2Qv9f=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipM0UR42n0pndo9TLYmQvv-k_svtoJqw0ycXzqV6=w408-h306-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipM1BscGy1JapS0w5U06fLwOZ5R-wcTHJDQtcIXq=s290-k-no',
        'https://lh5.googleusercontent.com/p/AF1QipPrrUSvN4XMeFCDVI1AqlkptpmGrXe1hQrYnd0q=s387-k-no'
      ];
      var locations = [
        'https://g.page/mezze-restaurant-aswan?share',
        'https://goo.gl/maps/Gi3w7Yj5wag4XKx96',
        'https://goo.gl/maps/wyxi7KM8XXscd9PM9',
        'https://goo.gl/maps/fLjhhjtJatH1UzWg6',
        'https://goo.gl/maps/aSs7vsM8St8KYGxs8',
        'https://g.page/makani-141?share',
        'https://goo.gl/maps/htyB2QJpM1nid4LJ9',
        'https://g.page/solaih?share',
        'https://goo.gl/maps/aw1DDt6cURfFW2jz5',
        'https://goo.gl/maps/VHYRXLa8qu1CEG1K9',
        'https://g.page/bob-marley-guesthouses?share',
        'https://goo.gl/maps/ZQvVmQ7kzphpaLvx7',
        'https://goo.gl/maps/zGBmJnKG8ssiL1xg6',
        'https://goo.gl/maps/SLfCd2HhLTKQWdKW7',
        'https://goo.gl/maps/4bCgKo47PMXGNZ9N6',
        'https://goo.gl/maps/s6TyG2SWa7fCTKRM8',
        'https://goo.gl/maps/r6t4P661SNqhhJVs5',
        'https://g.page/ibiza-nubian-house-restaurants?share',
        'https://goo.gl/maps/Got85i9JkfAcFsex9',
        'https://goo.gl/maps/X8z2kDfCJUxEBEa38',
        'https://goo.gl/maps/FBhw3hGrFKiz4ftH9',
        'https://g.page/alexandria-more-and-more?share',
        'https://goo.gl/maps/erYkSzm8uXFfBqTc8',
        'https://g.page/esmo-eh?share',
        'https://g.page/grand-restaurant-cafe-912?share',
        'https://goo.gl/maps/eit6WsYPSXgWBqdWA',
        'https://goo.gl/maps/CLsSYX6NY29MsQ1o9',
        'https://goo.gl/maps/HYkVeA5qrwqs9uEF7',
        'https://goo.gl/maps/N9KdGt5RhBWeUFRL9',
        'https://goo.gl/maps/NW5k7ZzbAYpAnt6aA',
        'https://goo.gl/maps/UHShVELynKu3Mihj6',
        'https://goo.gl/maps/spGMmrMMvLNrs4oAA',
        'https://goo.gl/maps/2jtEuxnSW4w1Pk129',
        'https://g.page/orangerie-restaurant-aswan?share',
        'https://goo.gl/maps/69Stcgno1MoifXfC7',
        'https://g.page/elephantine-restaurant?share',
        'https://goo.gl/maps/KT4DtfMztRbkLLR96',
        'https://goo.gl/maps/VZeWTBHW8JEo7kFE7',
        'https://goo.gl/maps/NBoXAVgzfGdpjhEP7',
        'https://goo.gl/maps/aYR8VCAkHawB7KBXA'
      ];
      var rates = [
        '5.0',
        '4.0',
        '4.0',
        '4.0',
        '4.0',
        '4.0',
        '4.5',
        '4.5',
        '4.5',
        '4.0',
        '5.0',
        '4.0',
        '4.0',
        '3.5',
        '5.0',
        '4.0',
        '3.5',
        '4.0',
        '4.5',
        '3.5',
        '4.5',
        '5.0',
        '5.0',
        '4.0',
        '4.0',
        '4.0',
        '3.0',
        '3.7',
        '4.0',
        '4.1',
        '4.0',
        '4.5',
        '4.0',
        '5.0',
        '4.0',
        '4.0',
        '4.8',
        '3.7',
        '3.9',
        ' 4.0'
      ];
      var lats = [
        '24.0939',
        '24.0828',
        '24.1144',
        '24.0926',
        '24.0988',
        '24.0852',
        '24.0895',
        '24.0230',
        '24.0995',
        '24.0831',
        '24.0906',
        '24.1274',
        '24.0927',
        '24.0985',
        '24.0360',
        '24.1048',
        '24.0905',
        '24.0927',
        '24.0728',
        '24.0991',
        '24.0663',
        '24.0946',
        '24.0978',
        '24.0891',
        '24.1032',
        '24.1006',
        '24.0987',
        '24.0883',
        '24.0935',
        '24.0954',
        '24.0907',
        '24.0905',
        '24.0929',
        '24.0935',
        '24.0886',
        '24.0939',
        '24.0921',
        '24.1093',
        '24.1019',
        '24.0974'
      ];
      var lngs = [
        '32.89267',
        '32.88459',
        '32.90008',
        '32.89922',
        '32.90056',
        '32.89106',
        '32.89109',
        '32.88349',
        '32.90130',
        '32.90426',
        '32.89157',
        '32.89504',
        '32.88827',
        '32.90213',
        '32.90463',
        '32.91463',
        '32.89532',
        '32.89066',
        '32.88749',
        '32.90280',
        '32.90954',
        '32.89687',
        '32.91188',
        '32.90040',
        '32.90182',
        '32.90132',
        '32.90133',
        '32.89347',
        '32.89206',
        '32.89765',
        '32.89223',
        '32.89624',
        '32.89857',
        '32.89220',
        '32.89357',
        '32.89261',
        '32.89568',
        '32.90206',
        '32.90255',
        '32.90167'
      ];
      // restaurants
      //     .add(
      //       {
      //         'Name': 'El Dokka',
      //         'Description':
      //             'This large temple complex, relocated to the island of Agilika with the building of the High Dam in Aswan, features the magnificent Temple of Isis that was built in the late Ptolemaic and early Roman periods.',
      //         'Location': 'https://goo.gl/maps/NYPoDTWUb7CazSrR8',
      //         'Rate': 4.0,
      //         'Image':
      //             'https://www.egypttoursportal.com/images/2017/11/Aswan-Nile-Rever-Egypt-Tours-Portal.jpg',
      //         'From': '7:00 AM',
      //         'To': '6:00 PM'
      //       },
      //     )
      //     .then((value) => print("restaurant Added"))
      //     .catchError((error) => print("Failed to add place: $error"));
      for (int i = 0; i < names.length; i++) {
        restaurants
            .add(
              {
                'Name': names[i],
                'Description': desc[i],
                'Location': locations[i],
                'Rate': double.parse(rates[i]),
                'Image': images[i],
                'From': froms[i],
                'To': tos[i],
                'Lat': double.parse(lats[i]),
                'Lng': double.parse(lngs[i]),
              },
            )
            .then((value) => print("restaurant Added"))
            .catchError((error) => print("Failed to add restaurant: $error"));
      }
      // temples
      //     .add(
      //       {
      //         'Name': 'Temple of Philae',
      //         'Description':
      //             'This large temple complex, relocated to the island of Agilika with the building of the High Dam in Aswan, features the magnificent Temple of Isis that was built in the late Ptolemaic and early Roman periods.',
      //         'Location': 'https://goo.gl/maps/g9Pcp7LTgc9Mc9FB9',
      //         'Rate': 4.5,
      //         'Image':
      //             'https://www.egypttoursportal.com/images/2017/11/Aswan-Nile-Rever-Egypt-Tours-Portal.jpg',
      //         'From': '7:00 AM',
      //         'To': '6:00 PM'
      //       },
      //     )
      //     .then((value) => print("temple Added"))
      //     .catchError((error) => print("Failed to add place: $error"));
      // places
      //     .add(
      //       {
      //         'Name': 'Aswan High Dam',
      //         'Description':
      //             'Supplying water and electricity to all of Egypt, this impressive two-mile dam was a 1960s feat of engineering.',
      //         'Location': 'https://goo.gl/maps/Eosi21PApj8mhh7r6',
      //         'Rate': 4.4,
      //         'Image':
      //             'https://cdn.britannica.com/34/76234-050-6176AC39/Aswan-High-Dam-Egypt.jpg',
      //         'From': '7:00 AM',
      //         'To': '2:00 PM'
      //       },
      //     )
      //     .then((value) => print("Place Added"))
      //     .catchError((error) => print("Failed to add place: $error"));
    }

    return TextButton(
      onPressed: () {
        addPlace();
        Navigator.pushNamed(context, '/createTour');
      },
      child: Text(
        "Add Places",
      ),
    );
  }
}
